### ISSUE TITLE
Scripting language

### ISSUE THREAD

**Issue by graphitemaster** [graphitemaster/neothyne#18]
I have a working lexer and parser. Need to consider a execution pipeline for it, maybe bytecode AOT or just execute on the AST directly.

**Comment by graphitemaster** [comment]
neolang has begun. The lexer and parser are complete. Working on writing the bytecode generator. Virtual machine and garbage collector + runtime will follow

**Comment by acerspyro** [comment]
woo

**Comment by graphitemaster** [comment]
Neo script is functioning and part of the scripting branch. Lots needs to be done before it's merged with master. Eliminating memory leaks. Improving performance and Integrating it correctly

**Comment by graphitemaster** [comment]
Closing because this is too vauge now that scripting is implemented
