### ISSUE TITLE
MD3 Rendering

### ISSUE THREAD

**Issue by graphitemaster** [graphitemaster/neothyne#28]

**Comment by graphitemaster** [comment]
IQM and OBJ is sufficient

**Comment by Calinou** [comment]
MD3 is really an obsolete format, like MDL, MD2 and MD5 are. There's no point in implementing it today. Assimp/open3mod will happily convert it to a modern format.

**Comment by acerspyro** [comment]
I don't see why I would use MD3 over IQM.

**Comment by graphitemaster** [comment]
Yeah I'm actually still on the fence about this.
