### ISSUE TITLE
Dynamic shadows

### ISSUE THREAD

**Issue by mtwilliams** [graphitemaster/neothyne#32]
I'll do this.

**Comment by graphitemaster** [comment]
Famous last words.

**Comment by mtwilliams** [comment]
Heh. I'll commit time this weekend or next. Likely the later because of my tight schedule.

Just bug me constantly!

**Comment by acerspyro** [comment]
Yo, m8, this is acerspyro, coming from the next, next, next, next, next, next, next, next, next, next, next, next, next, next, next, next, next, next weekend dawg. You done?

**Comment by graphitemaster** [comment]
We'll have to call them great, great, great, great, great, great, great, great, great, great, great, great, great, great, great, great, great, great grandfather shadows.

**Comment by mtwilliams** [comment]
:two_hearts:

**Comment by graphitemaster** [comment]
Implemented by eihrul ages ago. Other issues are opened to support it on map models and the sun light.
