### ISSUE TITLE
Use separate FOV value for hudguns

### ISSUE THREAD

**Issue by acerspyro** [graphitemaster/neothyne#34]
Doing so should prevent the hudguns from looking stretched.

**Comment by graphitemaster** [comment]
The HUD guns don't looked stretched, they look correct. Do you have a specific example in mind?

**Comment by acerspyro** [comment]
Well usually, in games, the hud gun is in a different viewspace than the rest of the world (To prevent the gun from ever clipping thru the walls and to change its FOV).

**Comment by graphitemaster** [comment]
The gun doesn't clip through walls because I set it to always pass the depth test. The field of view option is tricky since it would require a separate view port for the HUD gun which means it won't be able to get world light contribution or cast shadows (once they're implemented.)

**Comment by graphitemaster** [comment]
This is not an issue
