### ISSUE TITLE
Slopes are treated as small stairs (when going downwards)

### ISSUE THREAD

**Issue by Calinou** [graphitemaster/neothyne#36]
Like in Quake and Quake 2, slopes are treated as small stairs when walking them downwards. This feels rather sloppy (no pun intended!) and makes it hard to control your movement while on slopes.

**Comment by graphitemaster** [comment]
The code which handles slope physics is the exact same method Quake world uses to handle slopes. What you're experiencing is the over powered acceleration a single movement in any direction makes and the fact there is no friction-term on surfaces yet to dampen initial velocity. Not much effort has gone into movement yet as the engine is currently a higher priority. This will be fixed once the game gets written, what is there now is only place holder.

**Comment by graphitemaster** [comment]
Not related to engine code and will be rewritten as game code later once we get the scripting language
