### ISSUE TITLE
Support loading of Quake 3 maps

### ISSUE THREAD

**Issue by acerspyro** [graphitemaster/neothyne#41]

**Comment by Calinou** [comment]
This would probably require the ability to load Quake 3 shader files too, which is a lot of work if you want all effects (like cubemap reflections).

**Comment by graphitemaster** [comment]
The engine won't support loading of Quake 3 maps to play them. It will have an option in the world creator to purely import the base mesh of them. This feature is not important yet though. We already have the option to do this with OBJ meshes which you can convert .maps to trivially.

**Comment by acerspyro** [comment]
Btw, I am NOT doing maps in Blender, so people will have to use the Quake
editor anyways.

**Comment by graphitemaster** [comment]
Not worth the complexity of adding in the engine. You can already trivially convert the files to OBJ mesges which the engine will import.
